name: dicoding_restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <=4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  awesome_notifications: ^0.9.0
  build_runner: ^2.4.7
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.1.0
  iconsax: ^0.0.8
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.0.1
  mockito: ^5.4.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  timezone: ^0.9.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/json/local_restaurant.json

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
